-- Student ID: 103200214
-- Name: Lachlan Taylor
-- 1/9/2021



-- SELECT NAME FROM SYS.DATABASES;

-- CREATE DATABASE NHDW0214;

-- USE NHDW0214;

-- SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- SELECT * FROM DBO.DWPATIENT;



------------------ DIMENSION TABLES ------------------



DROP TABLE IF EXISTS DWPATIENT;
GO

CREATE TABLE DWPATIENT
(
    DWPATIENTID INTEGER NOT NULL,
    URNUMBER NVARCHAR(50) NOT NULL,
    DWSOURCEBD NVARCHAR(50) NOT NULL,
    DWSOURCETABLE NVARCHAR(50) NOT NULL,
    GENDER NVARCHAR(6) NOT NULL
        CHECK(GENDER IN ('Male','Female','Other')),
    DOB DATE NOT NULL,
    SUBURB NVARCHAR(50) NOT NULL,
    POSTCODE NVARCHAR(4) NOT NULL,
    COUNTRYOFBIRTH NVARCHAR(50) NOT NULL,
    PREFFEREDLANGUAGE NVARCHAR(50) NOT NULL,
    LIVESALONE NVARCHAR(3) NOT NULL
        CHECK(LIVESALONE IN ('Yes','No')),
    ACTIVE NVARCHAR(3) NOT NULL
        CHECK(ACTIVE IN ('Yes','No')),
    CATEGORYID INTEGER NOT NULL,
    CATEGORYNAME NVARCHAR(255) NOT NULL,
    PROCEDUREDATE DATETIME NOT NULL,
    DIAGNOSIS NVARCHAR(500) NOT NULL,
    PRIMARY KEY (DWPATIENTID)
);

GO



DROP TABLE IF EXISTS DWSTAFF;
GO

CREATE TABLE DWSTAFF
(
    DWSTAFFID INTEGER NOT NULL,
    STAFFID INTEGER NOT NULL,
    DWSOURCEBD NVARCHAR(50) NOT NULL,
    DWSOURCETABLE NVARCHAR(50) NOT NULL,
    ROLEID INTEGER NOT NULL,
    STAFFTYPE NVARCHAR(50) NOT NULL,
    PRIMARY KEY (DWSTAFFID)
);

GO



DROP TABLE IF EXISTS DWMEASUREMENT;
GO

CREATE TABLE DWMEASUREMENT
(
    DWMEASUREMENTID INTEGER NOT NULL,
    MEASUREMENTID INTEGER NOT NULL,
    DATAPOINTNUMBER INTEGER NOT NULL,
    DWSOURCEBD NVARCHAR(50) NOT NULL,
    DWSOURCETABLE NVARCHAR(50) NOT NULL,
    MEASUREMENTNAME NVARCHAR(50) NOT NULL,
    [NAME] NVARCHAR(50) NOT NULL,
    UPPERLIMIT INTEGER NOT NULL,
    LOWERLIMIT INTEGER NOT NULL,
    QUESTION NVARCHAR(255) NOT NULL,
    ANSWERNUMBER INTEGER NULL,
    PRIMARY KEY (DWMEASUREMENTID)
);

GO



DROP TABLE IF EXISTS DWRECORDTYPE;
GO

CREATE TABLE DWRECORDTYPE
(
    DWRECORDTYPEID INTEGER NOT NULL,
    RECORDTYPEID INTEGER NOT NULL,
    RECORDCATEGORYID INTEGER NOT NULL,
    DWSOURCEBD NVARCHAR(50) NOT NULL,
    DWSOURCETABLE NVARCHAR(50) NOT NULL,
    RECORDTYPE NVARCHAR(50) NOT NULL,
    [CATEGORY] INTEGER NOT NULL,
    PRIMARY KEY (DWRECORDTYPEID)
);

GO



------------------ FACT TABLES ------------------



DROP TABLE IF EXISTS DWTREATING;
GO

CREATE TABLE DWTREATING
(
    DWPATIENTID INTEGER NOT NULL,
    DWSTAFFID INTEGER NOT NULL,
    STARTDATE DATETIME NOT NULL,
    ENDDATE DATETIME NULL,
    PRIMARY KEY (DWPATIENTID, DWSTAFFID, STARTDATE)
);

GO



DROP TABLE IF EXISTS DWINTERVENTION;
GO

CREATE TABLE DWINTERVENTION
(
    DWPATIENTID INTEGER NOT NULL,
    DWSTAFFID INTEGER NOT NULL,
    [DATETIME] DATETIME NOT NULL,
    RECORDTYPEID INTEGER NOT NULL,
    RECORDTYPE NVARCHAR(50) NOT NULL,
    PRIMARY KEY (DWPATIENTID, DWSTAFFID, [DATETIME])
);

GO



DROP TABLE IF EXISTS DWMEASUREMENT;
GO

CREATE TABLE DWMEASUREMENT
(
    DWPATIENTID INTEGER NOT NULL,
    DWDATAPOINTID INTEGER NOT NULL,
    [DATETIME] DATETIME NOT NULL,
    [VALUE] FLOAT(10) NOT NULL,
    PRIMARY KEY (DWPATIENTID, DWDATAPOINTID, [DATETIME])
);

GO



CREATE TABLE DWDATE
(   
	[DATETIME] DATETIME NOT NULL, 
     PRIMARY KEY ([DATETIME])
    
);




-- SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- SELECT * FROM DBO.DWPATIENT;
-- SELECT * FROM DBO.DWSTAFF;
-- SELECT * FROM DBO.DWDATAPOINT;
-- SELECT * FROM DBO.DWTREATING;
-- SELECT * FROM DBO.DWINTERVENTION;
-- SELECT * FROM DBO.DWMEASUREMENT;


