-- Student ID: 103200214
-- Name: Lachlan Taylor
-- 1/9/2021



-- SELECT NAME FROM SYS.DATABASES;

-- CREATE DATABASE NHDW0214;

-- USE NHDW0214;

-- SELECT * FROM INFORMATION_SCHEMA.TABLES;

-- SELECT * FROM DBO.DWPATIENT;




DROP TABLE IF EXISTS DWPATIENT;
GO

CREATE TABLE DWPATIENT (
    DWPATIENTID         INTEGER IDENTITY(1,1)   NOT NULL,
    URNUMBER            NVARCHAR(50)    NOT NULL,  
    GENDER              NVARCHAR(50)    NOT NULL 
                        CHECK(GENDER IN ('Male','Female','Other')), 
    DOB                 DATETIME        NOT NULL, 
    SUBURB              NVARCHAR(50)    NOT NULL, 
    POSTCODE            NVARCHAR(4)     NOT NULL,
    COUNTRYOFBIRTH      NVARCHAR(50)    NOT NULL, 
    PREFFEREDLANGUAGE   NVARCHAR(50)    NOT NULL,
    LIVESALONE          NVARCHAR(3)     NOT NULL, 
    ACTIVE              NVARCHAR(3)     NOT NULL,
    CATEGORYID          INTEGER         NOT NULL,
    CATEGORYNAME        NVARCHAR(255)   NOT NULL, 
    PROCEDUREDATE       DATETIME        NOT NULL,
    PRIMARY KEY (DWPATIENTID)
    );

GO





